version: '3.9'

services:
  database:
    # Registers hostname in localdev network this must be unique
    hostname: ${POSTGRES_HOST}
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=${TIME_ZONE}
    restart: always
    ports:
      - ${DOCKER_DB_PORT:-5433}:${POSTGRES_PORT:-5432}
    networks:
      - localdev
    volumes:
      - lms-database:/var/lib/postgresql/data
    env_file:
      - ./.env

  api:
    image: mcr.microsoft.com/dotnet/sdk:7.0
    build: 
      context: .
      dockerfile: ./docker/api/Dockerfile
    depends_on:
      - database
    ports:
      - "${DOTNET_PORT-5005}:5005"
    networks:
      - localdev
    environment:
      - DOTNET_WATCH_RESTART_ON_RUDE_EDIT=1
      - ASPNETCORE_ENVIRONMENT=Development
      - TZ=${TIME_ZONE}
      - ConnectionStrings__DefaultConnection=User ID=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Server=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_DB}; IntegratedSecurity=true;Pooling=true;
      - DOTNET_CLI_TELEMETRY_OPTOUT = 1
    volumes:
      - ./services/api:/api
    working_dir: /api
    command: dotnet watch
    tty: true
    env_file:
      - ./.env
    restart: always

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - api
    restart: always
    volumes:
      - ./services/web:/web
    tty: true
    ports:
      - ${NODE_PORT:-81}:5173
    env_file:
      - ./.env
    networks:
      - localdev
    

networks:
  localdev:

volumes:
  lms-database: